name: Code Quality Checks

on: pull_request

jobs:
  code_format:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group dev --no-install-project

      - name: Run code formatter
        run: uv run isort . && uv run black .

      - name: Assert that the codebase has no diff
        shell: bash
        run: |
          if [[ -n "$(git status --short | grep '^ [^\s]\|??')" ]]; then
            echo "Unstaged/untracked files exist"
            git status
            git --no-pager diff
            echo "Auto formatting hasn't been applied by the codebase."
            exit 1
          fi
