name: Publish docs via GitHub Pages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_to:
        description: "Deployment destination"
        type: choice
        options:
          - prod
          - preview

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group docs

      - name: Build docs
        run: uv run mkdocs build --config-file mkdocs.yml

      - name: Fix site permissions
        if: github.event.action != 'closed'
        run: |
          sudo chown -R runner:runner site/
          find site/ -type f -exec chmod 644 {} \;
          find site/ -type d -exec chmod 755 {} \;

      - uses: rossjrw/pr-preview-action@v1
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.deploy_to == 'preview')
        with:
          source-dir: ./site/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

      - uses: JamesIves/github-pages-deploy-action@v4
        if: (github.event_name == 'push' && github.ref_name == 'main') ||  (github.event_name == 'workflow_dispatch' && inputs.deploy_to == 'prod')
        with:
          folder: ./site/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
